#!/usr/bin/env sh
# Regenerates Generated/ from spec/openapi.json using openapi-generator-cli (see /openapitools.json).
# The generator's own DI extensions (Extensions/), test project and csproj are intentionally
# not copied: dependency injection is provided by ServiceCollectionExtensions.cs.
set -eu

OUT="$(mktemp -d)"
TAGGED="$(mktemp)"
CONFIG="$(mktemp)"
trap 'rm -rf "$OUT" "$TAGGED" "$CONFIG"' EXIT

# The spec's operations carry no tags, so the generator hardcodes the api class name
# (DefaultApi, see DefaultCodegen.toApiName). Tag every operation with the tag the spec
# itself already declares at root level ("Agent Memory", "Agent Memory knowledge layer")
# via a temporary spec file — spec/openapi.json stays untouched — so the class comes out
# as AgentMemoryApi / IAgentMemoryApi. Drop this when the upstream spec tags its operations.
node -e '
const fs = require("fs");
const spec = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
for (const item of Object.values(spec.paths || {}))
    for (const m of ["get", "put", "post", "delete", "options", "head", "patch", "trace"])
        if (item[m]) item[m].tags = ["Agent Memory"];
fs.writeFileSync(process.argv[2], JSON.stringify(spec, null, 2));
' spec/openapi.json "$TAGGED"

openapi-generator-cli generate \
    -g csharp \
    -i "$TAGGED" \
    -o "$OUT" \
    --additional-properties 'library=generichost,packageName=SurrealDb.AgentMemory,packageVersion=0.2.1,nullableReferenceTypes=true,netCoreProjectFile=true,optionalProjectFile=false,optionalAssemblyInfo=false'

rm -rf Generated
mkdir -p Generated

for dir in Api Client Logging Model; do
    cp -r "$OUT/src/SurrealDb.AgentMemory/$dir" Generated/
done

# Only used by the generator's own (uncopied) DI extensions; not nullable-clean.
rm Generated/Client/HostConfiguration.cs

# Nested per-model enums are all named KindEnum; a single source-generation context
# collides on the shared simple name (SYSLIB1031). Rename each to a unique <Model>KindEnum
# (wire format is unaffected: JSON names come from the enum value mapping, not the type name).
for f in $(grep -rl 'enum KindEnum' Generated/Model); do
    name="$(basename "$f" .cs)"
    sed -i "s/\bKindEnum\b/${name}KindEnum/g" "$f"
done
sed -i -E 's/\b([A-Za-z0-9]+)\.KindEnum\b/\1.\1KindEnum/g' Generated/Client/ClientUtils.cs

# --- Emit AOT-safe JSON defaults from the fresh output -------------------------------------
# Explicit converter registrations + a source-generation context for every model.
# Replaces runtime reflection (Assembly.GetTypes + Activator) so the client works
# under trimming and NativeAOT. The diff of this file is the review surface when
# the spec changes: new models appear as new [JsonSerializable] entries.
# Top-level declarations sit at 4-space indent inside the block namespace; this anchor
# excludes nested helper types (e.g. the per-OneOf `KindEnum` classes), which must not
# become [JsonSerializable] roots (name collisions: SYSLIB1031).
MODELS="$(
    grep -rhoE '^    public (partial )?(class|enum) [A-Za-z0-9_]+' Generated/Model \
        | awk '{ print $NF }' \
        | grep -v 'JsonConverter$' \
        | sort -u
)"
CONVERTERS="$(
    grep -rhoE '^    public (partial )?class [A-Za-z0-9_]+' Generated/Model Generated/Client \
        | awk '{ print $NF }' \
        | grep 'JsonConverter$' \
        | sort -u
)"
# Closed generics (de)serialized inside converters (List<X>, Dictionary<...>) are never
# reached from model property graphs — root them explicitly so runtime lookups never miss.
# `object` is rooted for the free-form (metadata/graphExpansion) properties, which resolve
# to JsonElement under source generation exactly as they do under reflection.
GENERICS="$(
    grep -rhoE 'JsonSerializer\.(Deserialize|Serialize)(Async)?<[A-Za-z0-9_ <>,?]+>' Generated/ \
        | sed -E 's/^JsonSerializer\.(Deserialize|Serialize)(Async)?<//; s/>$//' \
        | grep '<' \
        | sort -u
)"

{
    cat <<'HEADER'
// <auto-generated>
// Emitted by generate.sh from the freshly generated models — do not edit by hand.
// Explicit converter registrations plus source-generation metadata for every model:
// no Assembly.GetTypes()/Activator reflection, so the client works under trimming and NativeAOT.

using System.Text.Json.Serialization;
using System.Collections.Generic;
using SurrealDb.AgentMemory.Model;

namespace SurrealDb.AgentMemory.Client;

/// <summary>
/// Source-generated serializer context covering every Agent Memory model, with every
/// generated converter pre-registered. <see cref="AgentMemoryJsonContext.Default"/>.Options
/// is the shared default used by the DI extensions.
/// </summary>
[JsonSourceGenerationOptions(Converters = new[]
{
HEADER
    printf '    typeof(%s),\n' $CONVERTERS
    printf '})]\n'
    printf '[JsonSerializable(typeof(%s))]\n' $MODELS
    # line-wise (not word-split) — generic type args contain spaces
    printf '%s\n' "$GENERICS" | while IFS= read -r g; do
        printf '[JsonSerializable(typeof(%s))]\n' "$g"
    done
    printf '[JsonSerializable(typeof(object))]\n'
    cat <<'FOOTER'
public partial class AgentMemoryJsonContext : JsonSerializerContext
{
}
FOOTER
} > Generated/Client/AgentMemoryJson.g.cs
# ---------------------------------------------------------------------------------------------

# The generator skips the marker on some hand-written support files; add it so analyzers/IDE treat every file under Generated/ as generated.
for f in $(find Generated -name '*.cs'); do
    head -1 "$f" | grep -q '<auto-generated>' || sed -i '1i\
// <auto-generated>' "$f"
done

# net9/net10 ILLink analyzers no longer honor the <auto-generated> marker for the options-based
# JsonSerializer calls the generator emits. Suppressing is safe here: every options instance the
# library passes carries AgentMemoryJsonContext as its resolver (see AgentMemoryJsonExtensions),
# so these call sites never reach the reflection serializer the annotations guard against.
for f in $(grep -rl 'JsonSerializer\.' Generated); do
    sed -i '1a #pragma warning disable IL2026, IL3050' "$f"
done

echo "Done. Review the diff, then bump <Version> in SurrealDb.AgentMemory.csproj if the spec version changed."
